version: "3.7"
services:
  web:
    image: vitcmun/munverse:latest
    container_name: munverse_container
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./media:/app/media
    env_file: .env
    environment:
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      NODE_ENV: production
    command: ["scripts/wait-for-it.sh", "mongo:27017", "--", "scripts/startup.sh"]
    ports:
      - "80:8080"
  mongo:
    image: mongo:4.2.3
    container_name: munverse_mongo
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
    volumes:
      - ./db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - dbdata:/data/db
volumes:
  dbdata: